// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  index: {
    name: "index",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    meta: undefined,
  },
  "swipe-row": {
    name: "swipe-row",
    description: "A swipe row for providing actions of swipe of left and right",
    type: "registry:ui",
    registryDependencies: ["utils"],
    files: [
      {
        path: "registry/molecule-ui/swipe-row.tsx",
        type: "registry:ui",
        target: "components/molecule-ui/swipe-row.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/molecule-ui/swipe-row.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  discussion: {
    name: "discussion",
    description:
      "A component for displaying nested discussions or comment threads.",
    type: "registry:ui",
    registryDependencies: ["utils"],
    files: [
      {
        path: "registry/molecule-ui/discussion.tsx",
        type: "registry:ui",
        target: "components/molecule-ui/discussion.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/molecule-ui/discussion.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "spinning-circle": {
    name: "spinning-circle",
    description:
      "A customizable spinning circle loader component for indicating loading states in your application. Features smooth animations and optional loading messages.",
    type: "registry:ui",
    registryDependencies: ["utils"],
    files: [
      {
        path: "registry/molecule-ui/spinning-circle.tsx",
        type: "registry:ui",
        target: "components/molecule-ui/spinning-circle.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/molecule-ui/spinning-circle.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "morphing-square": {
    name: "morphing-square",
    description:
      "A customizable morphing square loader component for indicating loading states in your application. Features smooth shape transitions and optional loading messages.",
    type: "registry:ui",
    registryDependencies: ["utils"],
    files: [
      {
        path: "registry/molecule-ui/morphing-square.tsx",
        type: "registry:ui",
        target: "components/molecule-ui/morphing-square.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/molecule-ui/morphing-square.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "orbital-loader": {
    name: "orbital-loader",
    description:
      "A customizable orbital loader component for indicating loading states in your application. Features smooth orbital animations and optional loading messages.",
    type: "registry:ui",
    registryDependencies: ["utils"],
    files: [
      {
        path: "registry/molecule-ui/orbital-loader.tsx",
        type: "registry:ui",
        target: "components/molecule-ui/orbital-loader.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/molecule-ui/orbital-loader.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "typewriter-loader": {
    name: "typewriter-loader",
    description:
      "A customizable typewriter loader component for indicating loading states in your application. Features smooth typing animations and customizable text content.",
    type: "registry:ui",
    registryDependencies: ["utils"],
    files: [
      {
        path: "registry/molecule-ui/typewriter-loader.tsx",
        type: "registry:ui",
        target: "components/molecule-ui/typewriter-loader.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/molecule-ui/typewriter-loader.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "swipe-row-demo": {
    name: "swipe-row-demo",
    description: "A preview component for swipe row",
    type: "registry:example",
    registryDependencies: ["https://moleculeui.design/r/swipe-row", "avatar"],
    files: [
      {
        path: "registry/example/swipe-row-demo.tsx",
        type: "registry:ui",
        target: "components/molecule-ui/example/swipe-row-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/swipe-row-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "swipe-row-left-demo": {
    name: "swipe-row-left-demo",
    description:
      "A demo component for adding actions only to left swipe in swipe row",
    type: "registry:example",
    registryDependencies: ["https://moleculeui.design/r/swipe-row", "avatar"],
    files: [
      {
        path: "registry/example/swipe-row-left-demo.tsx",
        type: "registry:ui",
        target: "components/molecule-ui/example/swipe-row-left-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/swipe-row-left-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "swipe-row-right-demo": {
    name: "swipe-row-right-demo",
    description:
      "A demo component for adding actions only to right swipe in swipe row",
    type: "registry:example",
    registryDependencies: ["https://moleculeui.design/r/swipe-row", "avatar"],
    files: [
      {
        path: "registry/example/swipe-row-right-demo.tsx",
        type: "registry:ui",
        target: "components/molecule-ui/example/swipe-row-right-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/swipe-row-right-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "swipe-row-list-demo": {
    name: "swipe-row-list-demo",
    description: "A group of Swipe Row representing a list view",
    type: "registry:example",
    registryDependencies: ["https://moleculeui.design/r/swipe-row", "avatar"],
    files: [
      {
        path: "registry/example/swipe-row-list-demo.tsx",
        type: "registry:ui",
        target: "components/molecule-ui/example/swipe-row-list-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/swipe-row-list-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "discussion-demo": {
    name: "discussion-demo",
    description: "Preview component for discussion demo",
    type: "registry:example",
    registryDependencies: [],
    files: [
      {
        path: "registry/example/discussion-demo.tsx",
        type: "registry:ui",
        target: "components/molecule-ui/example/discussion-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/discussion-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "spinning-circle-demo": {
    name: "spinning-circle-demo",
    description:
      "A demo component showcasing a spinning circle loading indicator",
    type: "registry:example",
    registryDependencies: ["https://moleculeui.design/r/spinning-circle"],
    files: [
      {
        path: "registry/example/spinning-circle-demo.tsx",
        type: "registry:ui",
        target: "components/molecule-ui/example/spinning-circle-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/spinning-circle-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "spinning-circle-with-message-demo": {
    name: "spinning-circle-with-message-demo",
    description:
      "A demo component showcasing a spinning circle loading indicator with message",
    type: "registry:example",
    registryDependencies: ["https://moleculeui.design/r/spinning-circle"],
    files: [
      {
        path: "registry/example/spinning-circle-with-message-demo.tsx",
        type: "registry:ui",
        target:
          "components/molecule-ui/example/spinning-circle-with-message-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/example/spinning-circle-with-message-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "morphing-square-demo": {
    name: "morphing-square-demo",
    description:
      "A demo component showcasing a morphing square loading indicator",
    type: "registry:example",
    registryDependencies: ["https://moleculeui.design/r/morphing-square"],
    files: [
      {
        path: "registry/example/morphing-square-demo.tsx",
        type: "registry:ui",
        target: "components/molecule-ui/example/morphing-square-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/morphing-square-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "morphing-square-with-message-demo": {
    name: "morphing-square-with-message-demo",
    description:
      "A demo component showcasing a morphing square loading indicator with message",
    type: "registry:example",
    registryDependencies: ["https://moleculeui.design/r/morphing-square"],
    files: [
      {
        path: "registry/example/morphing-square-with-message-demo.tsx",
        type: "registry:ui",
        target:
          "components/molecule-ui/example/morphing-square-with-message-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/example/morphing-square-with-message-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "orbital-loader-demo": {
    name: "orbital-loader-demo",
    description: "A demo component showcasing a orbital loading indicator",
    type: "registry:example",
    registryDependencies: ["https://moleculeui.design/r/orbital-loader"],
    files: [
      {
        path: "registry/example/orbital-loader-demo.tsx",
        type: "registry:ui",
        target: "components/molecule-ui/example/orbital-loader-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/orbital-loader-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "orbital-loader-with-message-demo": {
    name: "orbital-loader-with-message-demo",
    description:
      "A demo component showcasing a orbital loading indicator with message",
    type: "registry:example",
    registryDependencies: ["https://moleculeui.design/r/orbital-loader"],
    files: [
      {
        path: "registry/example/orbital-loader-with-message-demo.tsx",
        type: "registry:ui",
        target:
          "components/molecule-ui/example/orbital-loader-with-message-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/example/orbital-loader-with-message-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "typewriter-loader-demo": {
    name: "typewriter-loader-demo",
    description:
      "A demo component showcasing a typewriter loading indicator demo",
    type: "registry:example",
    registryDependencies: ["https://moleculeui.design/r/typewriter-loader"],
    files: [
      {
        path: "registry/example/typewriter-loader-demo.tsx",
        type: "registry:ui",
        target: "components/molecule-ui/example/typewriter-loader-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/typewriter-loader-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "typewriter-loader-with-custom-text-demo": {
    name: "typewriter-loader-with-custom-text-demo",
    description:
      "A demo component showcasing a typewriter loading indicator with custom text demo",
    type: "registry:example",
    registryDependencies: ["https://moleculeui.design/r/typewriter-loader"],
    files: [
      {
        path: "registry/example/typewriter-loader-with-custom-text-demo.tsx",
        type: "registry:ui",
        target:
          "components/molecule-ui/example/typewriter-loader-with-custom-text-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/example/typewriter-loader-with-custom-text-demo.tsx"
      )
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "profile-menu-demo": {
    name: "profile-menu-demo",
    description: "Demo for the animated profile menu",
    type: "registry:example",
    registryDependencies: [],
    files: [
      {
        path: "registry/example/profile-menu-demo.tsx",
        type: "registry:ui",
        target: "components/molecule-ui/example/profile-menu-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/profile-menu-demo.tsx")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  utils: {
    name: "utils",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/lib/utils.ts",
        type: "registry:lib",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/utils.ts")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
}
