import { exec } from "child_process"
import { promises as fs } from "fs"
import path from "path"
import { rimraf } from "rimraf"
import { registryItemSchema, type Registry } from "shadcn/registry"
import { z } from "zod"

/* eslint-disable no-relative-import-paths/no-relative-import-paths */
import { componentRegistry } from "../registry/index.ts"

const registry = {
  name: "Molecule UI",
  homepage: "https://moleculeui.design",
  items: z.array(registryItemSchema).parse([
    {
      name: "index",
      type: "registry:style",
      dependencies: [
        "tw-animate-css",
        "class-variance-authority",
        "lucide-react",
      ],
      registryDependencies: ["utils"],
      cssVars: {},
      files: [],
    },
    ...componentRegistry,
  ]),
} satisfies Registry

async function buildRegistryIndex() {
  let index = `
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {`
  for (const item of registry.items) {
    const resolveFiles = item.files?.map((file) => `${file.path}`)
    if (!resolveFiles) {
      continue
    }

    const componentPath = item.files?.[0]?.path ? `@/${item.files[0].path}` : ""

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ""}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    files: [${item.files?.map((file) => {
      const filePath = `${typeof file === "string" ? file : file.path}`
      const resolvedFilePath = path.resolve(filePath)
      return typeof file === "string"
        ? `"${resolvedFilePath}"`
        : `{
      path: "${filePath}",
      type: "${file.type}",
      target: "${file.target ?? ""}"
    }`
    })}],
    component: ${
      componentPath
        ? `React.lazy(async () => {
      const mod = await import("${componentPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    })`
        : "null"
    },
    meta: ${JSON.stringify(item.meta)},
  },`
  }

  index += `
  }`

  // Write style index.
  rimraf.sync(path.join(process.cwd(), "registry/__index__.tsx"))
  await fs.writeFile(path.join(process.cwd(), "registry/__index__.tsx"), index)
}

async function buildRegistryJsonFile() {
  const fixedRegistry = {
    ...registry,
    items: registry.items.map((item) => {
      const files = item.files?.map((file) => {
        return { ...file, path: `${file.path}` }
      })

      return { ...item, files }
    }),
  }

  rimraf.sync(path.join(process.cwd(), `registry.json`))
  rimraf.sync(path.join(process.cwd(), `public/registry.json`))

  const registryJson = JSON.stringify(fixedRegistry, null, 2)

  await fs.writeFile(path.join(process.cwd(), `registry.json`), registryJson)
  await fs.writeFile(
    path.join(process.cwd(), `public/registry.json`),
    registryJson,
  )
}

async function buildRegistry() {
  return new Promise((resolve, reject) => {
    const process = exec(`pnpm shadcn:build`)

    process.on("exit", (code) => {
      if (code === 0) {
        resolve(undefined)
      } else {
        reject(new Error(`Process exited with code ${code}`))
      }
    })
  })
}

try {
  console.log("🗂️ Building registry/__index__.tsx...")
  await buildRegistryIndex()
  console.log("✅ Registry index built successfully")

  console.log("💅 Building registry.json...")
  await buildRegistryJsonFile()
  console.log("✅ Registry JSON file built successfully")

  console.log("🏗️ Building registry...")
  await buildRegistry()
  console.log("✅ Registry build completed")
} catch (error) {
  if (error instanceof Error) {
    console.error("Error stack:", error.stack)
  }
  process.exit(1)
}
